### ISSUE TITLE
Failing on MacOS X 10.12.2: 'dbus/dbus.h' file not found

### ISSUE THREAD

**Issue by ajmas** [Shouqun/node-dbus#144]
I am trying to build 'serve-index' on MacOS X, which brings in dbus. During this phase I get the following failure:

```
> dbus@0.2.20 install /Users/ajmas/Development/projects/Experimental-NodeJS/node_modules/dbus
> node-gyp configure build

  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/dbus/src/dbus.o
../src/dbus.cc:6:10: fatal error: 'dbus/dbus.h' file not found
#include <dbus/dbus.h>
         ^
1 error generated.
make: *** [Release/obj.target/dbus/src/dbus.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.3.0
gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/ajmas/Development/projects/Experimental-NodeJS/node_modules/dbus
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN install:dbus@0.2.20 dbus@0.2.20 install: `node-gyp configure build`
npm WARN install:dbus@0.2.20 Exit status 1
keypress@0.1.0 node_modules/keypress -> node_modules/upnpserver/node_modules/commander/node_modules/keypress
argus@0.0.3 node_modules/argus -> node_modules/upnpserver/node_modules/status/node_modules/argus
fractal@0.0.3 node_modules/fractal -> node_modules/upnpserver/node_modules/status/node_modules/fractal
loggo@0.0.4 node_modules/loggo -> node_modules/upnpserver/node_modules/status/node_modules/loggo
semver@4.3.6 node_modules/semver -> node_modules/upnpserver/node_modules/status/node_modules/semver
experimental-node-js@0.0.1 /Users/ajmas/Development/projects/Experimental-NodeJS
└── serve-index@1.8.0 
```

I do have dbus installed my by means of MacPorts (I have attached a manifest of installed files). Node version is 6.7.0

I also tried doing a symlink of /opt/local/include/dbus-1.0/dbus to /opt/local/include/dbus

Any ideas?

Attached:
 - [dbus-installed-files.txt](https://github.com/Shouqun/node-dbus/files/721292/dbus-installed-files.txt)
 - Output of trying ``npm install`` on node-dbus clone: [npm-debug.log.txt](https://github.com/Shouqun/node-dbus/files/721310/npm-debug.log.txt)

**Comment by ajmas** [comment]
Looks for MacPorts updating binding.gyp with the following allows it to build:
```
      'include_dirs': [
        "<!(node -e \"require('nan')\")",
        "/opt/local/include/dbus-1.0",
        "/opt/local/lib/dbus-1.0/include"
      ],
```

I can submit a PR request, along with doc update?
