### ISSUE TITLE
Errors when installing on 32bit system

### ISSUE THREAD

**Issue by fcastilloec** [Shouqun/node-dbus#172]
I'm trying to add `dbus` but I keep getting errors. I do have both `libdbus-1-dev`, `libglib2.0-dev` and `node-gyp@3.4.0` installed on my system (Linux Mint Cinnamon -18.2- Sonya 32bit). Here's the output when running `npm install dbus`
```
> dbus@1.0.0 install /home/felipe/node_modules/dbus
> node-gyp configure build

make: Entering directory '/home/felipe/node_modules/dbus/build'
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
../deps/libexpat/lib/xmlparse.c: In function ‘gather_time_entropy’:
../deps/libexpat/lib/xmlparse.c:709:7: warning: variable ‘gettimeofday_res’ set but not used [-Wunused-but-set-variable]
   int gettimeofday_res;
       ^
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  AR(target) Release/obj.target/deps/libexpat/libexpat.a
  COPY Release/libexpat.a
  CXX(target) Release/obj.target/dbus/src/dbus.o
make: g++: Command not found
dbus.target.mk:113: recipe for target 'Release/obj.target/dbus/src/dbus.o' failed
make: *** [Release/obj.target/dbus/src/dbus.o] Error 127
make: Leaving directory '/home/felipe/node_modules/dbus/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.10.0-32-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/felipe/node_modules/dbus
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN felipe No description
npm WARN felipe No repository field.
npm WARN felipe No license field.
npm ERR! Linux 4.10.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "dbus"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! dbus@1.0.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dbus@1.0.0 install script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dbus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dbus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dbus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/felipe/workspace/dbus/npm-debug.log
```
Here's the log file mentioned at the end of that error message [npm-dbug.log](https://gist.github.com/fcastilloec/55a2c6ef21cd8881e50c5bb7e96185f3)

**Comment by fcastilloec** [comment]
My bad... g++ was not installed
